# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :internal do |options|
    increment_version_code(
         gradle_file_path: "./app/build.gradle",
    )
    
    make_changelog_from_jenkins(
        fallback_changelog: "In this version, we add release notes from internal task itself"
    )

    gradle(task: "clean bundleRelease")

    upload_to_play_store(
        track:'internal',
        version_name: options[:versionName]
    )

    git_add(path: "./app/build.gradle")
    git_commit(path: "./app/build.gradle", message: "Up version code")
    push_to_git_remote(
        remote: "origin"
    )
  end
end
