# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :internal do |options|
    newVersionCode = increment_version_code(
         gradle_file_path: "./app/build.gradle",
    )

    sh("echo \"#{options[:releaseNotes]}\" >> metadata/android/en-US/changelogs/#{newVersionCode}.txt")

    gradle(task: "clean bundleRelease")

    upload_to_play_store(
        track:'internal',
        version_name: options[:versionName]
    )

    git_add(path: "./app/build.gradle")
    git_commit(path: "./app/build.gradle", message: "Up version code")
    push_to_git_remote(
        remote: "origin"
    )
  end

  lane :git_message_tag do
    last_tag = last_git_tag
    result = sh("git tag -l --format='%(contents)' #{last_tag}")
    print("this is tag message: #{result}")
  end
end
